name: ROS2

channels:
  - conda-forge
  - pytorch
  - pypi

dependencies:
  # Python Interpreter
  - python >= 3.12
  - pip

  # Utilities
  - tqdm
  - termcolor

  # Basic algebra and image processing
  - numpy
  - pillow
  - opencv

  # Machine learning framework and models
  - pytorch
  - torchvision
  - ultralytics
  - open-clip-torch
