# mode: localization

# use_map_saver: false

# # if you'd like to immediately start continuing a map at a given pose
# # or at the dock, but they are mutually exclusive, if pose is given
# # will use pose
map_file_name: map
# map_update_interval: 1.0
map_start_pose: [0.0, 0.0, 0.0]
# map_start_at_dock: true

do_loop_closing: false

# # Scan Matcher Parameters
# distance_variance_penalty: 0.0
# angle_variance_penalty: 0.0
