#include "protocol.h"

#define NAME(NAME) template <> const char *MSP::NAME::name = #NAME

namespace MultiWii {
NAME(REBOOT);
NAME(IDENT);
NAME(STATUS);
NAME(RAW_IMU);
NAME(SERVO);
NAME(MOTOR);
NAME(RC);
NAME(RAW_GPS);
NAME(COMP_GPS);
NAME(ATTITUDE);
NAME(ALTITUDE);
NAME(ANALOG);
NAME(RC_TUNING);
NAME(PID);
NAME(BOX);
NAME(MISC);
NAME(MOTOR_PINS);
NAME(SET_RAW_RC);
NAME(SET_RAW_GPS);
NAME(SET_PID);
NAME(SET_BOX);
NAME(SET_RC_TUNING);
NAME(ACC_CALIBRATION);
NAME(MAG_CALIBRATION);
NAME(SET_MISC);
NAME(RESET_CONF);
NAME(SET_HEAD);
NAME(SET_MOTOR);
NAME(BIND);
NAME(EEPROM_WRITE);
} // namespace MultiWii
