#!/bin/bash
# First argument: path to all images
DIR=$1
if [ -z "$DIR" ]; then
  echo "usage: $0 path/to/image/dir"
  exit 1
fi

if ! test -d "$DIR"; then
  echo "directory \"$DIR\" not found"
  echo
  echo "usage: $0 path/to/image/dir"
  echo
  exit 1
fi

OUTPUT=$2
if [ -z "$OUTPUT" ]; then
  OUTPUT=$DIR.mp4
fi

OUTPUT=$(realpath $OUTPUT)

if [ -z "$SUFFIX" ]; then
  SUFFIX=png
fi

ffmpeg \
  -framerate 20 \
  -pattern_type glob \
  -i "$DIR/*.${SUFFIX}" \
  -c:v libx264 -preset medium -profile:v main \
  -vf format=yuv420p \
  -crf 10 \
  $OUTPUT \
&& rm -r $DIR \
&& echo "============================================" \
&& echo "Video encoded: $OUTPUT" \
&& echo "============================================"
